/**
 * test-installed-shapes-historical.test.ts — T4.5.3 historical-shapes
 * regression for `.jumpstart/installed.json`.
 *
 * Asserts that 10 historical shapes (representing every recorded
 * format the installed.json ledger has gone through across
 * jumpstart-mode 0.1—1.x) parse cleanly via `readInstalled` and
 * round-trip byte-identical via `writeInstalled` → `readFileSync`.
 *
 * Why it matters: a downstream user upgrading from 0.5 → 2.0 will
 * have a 0.5-shape installed.json on disk. The TS port must accept
 * that shape AND the upgrade flow must preserve the bytes (so a
 * subsequent `getStatus` doesn't re-write a different-but-equivalent
 * file just because the in-memory shape was normalized).
 *
 * The 10 fixtures are generated by
 * `tests/fixtures/installed-shapes/build-fixtures.mjs` — a
 * deterministic generator. Re-run the script after intentional shape
 * changes; commit the .json files alongside the test.
 *
 * @see specs/implementation-plan.md T4.5.3
 * @see src/lib/install.ts (readInstalled / writeInstalled)
 */

import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { readInstalled, writeInstalled } from '../src/lib/install.js';

const FIXTURES_DIR = path.join(__dirname, 'fixtures', 'installed-shapes');

let tmpDir: string;

beforeEach(() => {
  tmpDir = mkdtempSync(path.join(tmpdir(), 'inst-shape-'));
  mkdirSync(path.join(tmpDir, '.jumpstart'), { recursive: true });
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

/** Discover all .json fixtures so adding new ones doesn't require a test edit. */
function listFixtures(): string[] {
  return readdirSync(FIXTURES_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();
}

describe('T4.5.3 — historical installed.json shapes parse + round-trip', () => {
  it('discovers 10 historical fixtures', () => {
    expect(listFixtures().length).toBe(10);
  });

  for (const fixture of listFixtures()) {
    describe(`fixture ${fixture}`, () => {
      it('parses to a valid InstalledData shape', () => {
        // Stage the fixture as `.jumpstart/installed.json` in a fresh project.
        const stagedPath = path.join(tmpDir, '.jumpstart', 'installed.json');
        const raw = readFileSync(path.join(FIXTURES_DIR, fixture), 'utf8');
        const fs = require('node:fs') as typeof import('node:fs');
        fs.writeFileSync(stagedPath, raw, 'utf8');

        const parsed = readInstalled(tmpDir);
        expect(parsed).toBeDefined();
        expect(parsed.items).toBeDefined();
        expect(typeof parsed.items).toBe('object');
        expect(Array.isArray(parsed.items)).toBe(false);
      });

      it('round-trips byte-identically through writeInstalled → readFile', () => {
        const stagedPath = path.join(tmpDir, '.jumpstart', 'installed.json');
        const raw = readFileSync(path.join(FIXTURES_DIR, fixture), 'utf8');
        const fs = require('node:fs') as typeof import('node:fs');
        fs.writeFileSync(stagedPath, raw, 'utf8');

        // Read in, write back.
        const data = readInstalled(tmpDir);
        writeInstalled(tmpDir, data);

        const written = readFileSync(stagedPath, 'utf8');
        expect(written).toBe(raw);
      });

      it('preserves every entry id from the fixture across round-trip', () => {
        const stagedPath = path.join(tmpDir, '.jumpstart', 'installed.json');
        const raw = readFileSync(path.join(FIXTURES_DIR, fixture), 'utf8');
        const fs = require('node:fs') as typeof import('node:fs');
        fs.writeFileSync(stagedPath, raw, 'utf8');

        const expectedIds = Object.keys(JSON.parse(raw).items || {}).sort();
        const data = readInstalled(tmpDir);
        const actualIds = Object.keys(data.items).sort();
        expect(actualIds).toEqual(expectedIds);
      });
    });
  }
});

describe('T4.5.3 — defense-in-depth: fixtures contain no secret-shaped strings', () => {
  // If a fixture accidentally embeds a secret-shaped string, redactSecrets
  // would alter the round-trip. Scan every fixture upfront and fail loudly
  // if one ever lands.
  for (const fixture of listFixtures()) {
    it(`${fixture} contains no GitHub PAT / AWS key / Slack token / Bearer token shape`, () => {
      const raw = readFileSync(path.join(FIXTURES_DIR, fixture), 'utf8');
      // Patterns mirror the DEFAULT_PATTERNS shapes in secret-scanner.ts.
      // If a fixture matches any of these, the round-trip test will fail
      // because writeInstalled scrubs them. Catch it here with a clearer
      // diagnostic.
      expect(raw).not.toMatch(/AKIA[0-9A-Z]{16}/);
      expect(raw).not.toMatch(/gh[ps]_[A-Za-z0-9_]{36,}/);
      expect(raw).not.toMatch(/github_pat_[A-Za-z0-9_]{22,}/);
      expect(raw).not.toMatch(/xoxb-[0-9]{10,}-[0-9]{10,}-[A-Za-z0-9]{24,}/);
      expect(raw).not.toMatch(/Bearer\s+[A-Za-z0-9_\-.]{20,}/i);
      expect(raw).not.toMatch(/-----BEGIN .*PRIVATE KEY-----/);
    });
  }
});
